### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by izabel1209**
Changed spelling error which was successfull to successful.

### CODE REVIEW

**Review by mampir — APPROVED** [review]
Thank you for fixing "successful". :)

**Review by mampir — CHANGES_REQUESTED** [review]
I've gotta say, the English in the original README written by Diana wasn't perfect, but the fixes you've added have a lot of problems too.

**Comment by mampir** [comment]
The Korean README you've wrote, I can't tell if it's good or not, but I'll assume it's good. Thank you! I'll merge it when we fix the English issues you've added - not sure what would be the best way to do that, since I'm not very familiar with this Pull system here. Maybe I'll just manually add the things you've fixed to our repository, and then you can fix the Pull request? :)

**Comment by mampir** [comment]
I merged and fixed the English language.

**Comment by TS-Logic** [comment]
Thanks!

**Comment by kimms320** [comment]
Cool~

**Pull request merged**
