### PR TITLE
Update main.cpp

### PR DESCRIPTION
**Pull request by simhj316**
The pacman_stay in pacman.cpp is only declared and not initialized. An error occurred when moving to the next level and deleted.

### CODE REVIEW

**Comment by simhj316** [comment]
Modified to give pacman a change when eating an energizer

**Review by mampir — APPROVED** [review]
Cool, thank you for finding and fixing this bug :)

**Review by mampir — CHANGES_REQUESTED** [review]
Happy to see you are improving stuff. :) Can you fix the following issues before we merge:

1. Don't use tabs for indentation in this project - we use only spaces.
2. What is this "count" variables? You should remove it if doesn't seem to do anything.
3. We need a res/hellpacman.png image - who's gonna draw it?

**Comment by TS-Logic** [comment]
hellpacman

hellpacman.png

**Review by mampir — CHANGES_REQUESTED** [review]
Thank you, but can you take care of the "count" variable I mentioned? Also, please make the indentation proper, like this:

        if (...) {
            line 1;
            line 2;
        }

Not like this:

        if (...) {
        line 1;
        line 2;
        }

Sorry for being pedantic about this, but it's basic stuff.

**Comment by simhj316** [comment]
Sorry, are you referring to the count in ghost.cpp? It represents being a hellpacman under the conditions of ghosts. So it's hard to erase.

**Comment by mampir** [comment]
You mean, it's used to check if there are any frightened ghosts, so we know when to draw hell or normal Pacman. The variable "count" is badly named, because it's not clear what it counts and in reality it doesn't count anything, because it's either 0 or 1 (FRIGHTENED or NOT FRIGHTENED). You don't need a separate variable for that, you can just use ghost.state == GHOST_FRIGHTENED.

Also, the way you declared "count", placed between 2 functions, and indented as if it's inside a function, isn't very nice.  You should have put it right after "public:", similar to how it's done in the ghost class.  And since every ghost has a "count", you should have put it in the ghost class instead, and not in 4 places.

I also checked the image, and it has graphical artifacts (white dots around it), which is very sloppy job...

I merged and fixed all that.

**Comment by TS-Logic** [comment]
Thank you for your devotion. This experience has given me a good study of cooperation.

**Comment by mampir** [comment]
Happy to help. Would like to see more stuff from you. :)

**Pull request merged**
